[tools]
"aqua:aws/aws-cli" = "2.22.20"
ibmcloud = "2.32.2"
oc = "stable-4.17"
"pipx:git+https://gitlab.cee.redhat.com/compute/aws-automation.git" = "latest"
"ubi:coreos/butane" = "latest"
"ubi:openshift/rosa" = "1.2.50"
"ubi:oras-project/oras" = "1.2.2"
