apiVersion: ibmcloud.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: ibm-cloud
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: provider-ibm-cloud-secret
      key: credentials
  region: us-east-1
